### ISSUE TITLE
Can't set value to select

### ISSUE THREAD

**Issue by vpugh** [pedrohidalgo/react-select-us-states#3]
I can't seem to get the value to be displayed on this input if I mount the component again? 
```
<SelectUSState name="state" id="state" className="" onChange={this.setNewValue} value={state} />
```
The onChange console logs but the value doesn't seem to be going down to the actual select input.

![screen shot 2018-12-04 at 12 16 16 pm](https://user-images.githubusercontent.com/5824579/49460057-78f57800-f7be-11e8-82c6-d023ff6a6314.png)

**Comment by JonVisc** [comment]
@vpugh How'd you get it to default to a selected value?  To me it always starts on Alabama.
